#   捕获异常

抛出异常很简单，但是有时候必须捕获异常。捕获异常需要进行周密的计划。

##  捕获异常

如果某个异常发生的时候没有在任何地方进行捕获，那程序就会终止执行，并在控制台上打印出异常信息，其中包括异常的类型和堆栈的内容。

要想捕获一个异常，必须设置 try/catch 语句块，最简单的 try 语句块如下所示：

```Java
try {
    // 。。。
} catch (ExceptionType e) {
    // 。。。
}
```

如果在 try 语句块中的任何代码抛出了一个在 catch 子句中说明的异常类，那么

-   程序将跳过 try 语句块的其余代码
-   程序将执行 catch 子句中的处理器代码

如果在 try 语句块中的代码没有抛出任何异常，那么程序将跳过 catch 子句。

一个读取数据的典型程序代码：

```Java
public void read(String filename) {
    try {
        InputStream in = new Filei叩utStream(filename) ;
        int b;
        while ((b = in.read()3 != -1) {
            //process input
        }
    } catch (IOException exception) {
        exception.printStackTrace();
    }
}
```

正如在 Java API 中看到的那样， read 方法有可能抛出一个 IOException 异常。在这种情况下，将跳出整个 while 循环，进入 catch 子句，并生成一个栈轨迹。

如果要将异常传递给调用者，就需要声明这个方法可能会抛出一个 IOException，如下所示：

```Java
public void read(String filename) throws IOException (
    InoutStream in = new FileInoutStream(filename) ;
    int b;
    while ((b = in.readO) != -1) {
        // process input
    }
}
```

编译器严格执行 throws 说明符，如果调用了一个抛出受查异常的方法，就必须对他进行处理，或者继续传递。通常，应该捕获那些知道如何处理的异常，而将那些不知道怎样处理的异常继续进行传递。

如果想传递一个异常，就必须在方法的首部添加一个 throws 说明符，以便告知调用者这个方法可能会抛出异常。

如果编写一个覆盖超类的方法，而这个方法又没有抛出异常，那么这个方法就必须捕获方法代码中出现的每一个受查异常，不允许在子类的 throws 说明符中出现超过超类方法所列出的异常类范围。


##  捕获多个异常

在一个 try 语句块中可以捕获多个异常类型，并对不同类型的异常做出不同的处理，可以按照下列方式为每个异常类型使用一个单独的 catch 子句：

```Java
try {
    code that might throw exceptions

}   catch (FileNotFoundException e) {
    emergencyactionfor missingfiles

}   catch (UnknownHostException e) {
    emergency actionfor unknown hosts

}   catch (IOException e) {
    emergencyactionfor all other I/O problems

}
```

异常对象可能包含与异常本身有关的信息，要想获得对象的更多信息，可以试着调用

```Java
// 详细得错误信息
e.getMessage();

// 异常对象的实际类型
e.getClass().getName();
```

在 Java SE 7 中，同一个 catch 子句中可以捕获多个异常类型，例如，假设对应缺少文件和未知主机异常的动作是一样的，就可以合并 catch 子句：

```Java
try {
    code that might throw exceptions
} catch (FileNotFoundException | UnknownHostException e) {
    emergency action for missing files and unknown hosts
}   catch (IOException e) {
    emergency action for all other I/O problems
}
```

只有当捕获的异常类型彼此之间不存在子类关系时才需要这个特性。

##  再次抛出异常与异常链

在 catch 子句中可以抛出一个异常，这样做的目的是改变异常的类型。

如果开发了一个供其他程序员使用的子系统，那么，用于表示子系统故障的异常类型可能会产生多种解释。 ServletException 就是这样一个异常类型的例子，执行 servlet 的代码可能不想知道发生错误的细节原因，但希望明确知道 servlet 是否有问题。

捕获异常并将它再次抛出的基本方法：

```Java
try {
    access the database
} catch (SQLException e) {
    throw new ServletException("database error: " + e.getMessageO) ;
}
```

ServletException 用带有异常信息文本的构造器来构造。

不过，可以用一种更好的处理方式，并且将原始异常设置为新异常的"原因"：

```Java
try {
    access the database
} catch (SQLException e)
    Throwable se = new ServletException ("database error")；
    se.ini tCause(e);
    throw se;
}
```

当捕获到异常时，就可以使用下面这条语句重新得到原始异常：

```Java
Throwable e = se.getCause();
```

这样可以让用户抛出子系统中的高级异常，而不会丢失原始异常的细节。

##  finally 子句

当代码抛出一个异常时，就会终止方法中剩余代码的处理，并退出这个方法的执行。

如果方法获得了一些本地资源，并且只有这个方法自己知道，并且这些资源在退出方法之前必须被回收，那么就会产品资源回收问题。

一种解决方案是捕获并重新抛出所有的异常，但是这需要在两个地方清除所分配的资源，一个是正常的代码中，另一个在异常代码中。

Java 有一种更好的解决方案，这就是 finally 子句。

不管是否有异常被捕获，finally 子句中的代码都被执行，如下所示，将在所有情况下关闭文件：

```Java
InputStream in = new FileInputStream(. . .);
try {
    // 1
    // 抛出异常
    // 2
} catch (IOException e) {
    // 3
    // 显示错误信息
    // 4
} finally {
    // 5
    // 释放资源
}
// 6
```

有3种情况会执行 finally 子句：

-   代码没有抛出异常，首先执行 try 语句块中的全部代码，然后执行 finally 子句中的代码
    -   即，标注的 1、2、5、6
-   抛出一个在 catch 子句中捕获的异常，执行 try 语句块中的所有代码，直到发生异常为止
    -   此时，将跳过 try 语句块中剩余代码，转去执行与该异常匹配的 catch 子句中的代码
    -   最后，执行 finally 子句的代码，即标注 1、3、4、5、6
    -   如果 catch 子句抛出了一个异常，异常将被抛回这个方法的调用者，即 1、3、5
-   代码抛出了一个异常，但这个异常不是由 catch 子句捕获的，执行 try 语句块中的所有代码，直到发生异常为止
    -   此时，将跳过 try 语句块中剩余代码，然后执行 finally 子句中的语句，并将异常抛给这个方法的调用者
    -   即标注 1、5

try 语句可以只有 finally 子句，而没有 catch 子句，如下所示：

```Java
InputStream in = 。。。;
try {
    ////
} finally {
    in.close();
}
```

无论在 try 语句块中是否遇到异常，finally 子句中的 in.close() 语句都会被执行。如果真的遇到一个异常，这个异常将会被重新抛出，并且必须由另一个 catch 子句捕获。

在需要关闭资源时，用这种方式使用 finally 子句是一种不错的选择。

```Java
// 解耦合 try/catch 和 try/finally 语句块
InputStream in = 。。。;
try {

    try {
        // 抛出异常了。。
    } finally {
        in.close();   
    }

} catch (IOException e) {
    // 显示错误信息
}
```

内层的 try 语句块只有一个职责，就是确保关闭输入流。外层的 try 语句块也只有一个职责，就是确保报告出现的错误，另外，还会报告finally 子句中出现的错误

当 finally 子句包含 return 语句时，将会出现一种意想不到的结果。

假设利用 return 语句从 try 语句块中退出，在方法返回前，finally 子句的内容将被执行。如果 finally 子句中也有一个 return 语句，这个返回值将会覆盖原始的返回值。

清理资源的方法也有可能抛出异常，假设希望能够确保在流处理代码中遇到异常时将流关闭。


##  带资源的try语句

假设资源属于一个实现了 AutoCloseable 接口的类，Java SE 7 为这种代码模式提供了一个很有用的快捷方式。

带资源的 try 语句(try-with-resources)的最简形式为：

```Java
try (Resources res = 。。) {
    /// 使用资源
}
```

try 块退出时，会自动调用 res.close()，例如：

```Java
try (Scanner in = new Scanner(new FileInputStream("usr/share/dict/words")) , "UTF-8") {
    while (in.hasNextO)
    System.out .pri ntl n(i n.next ()) ;
}
```

这个快正常退出时，或者存在一个异常时，都会调用 in.close() 方法，就好像使用了 finally 块一样。

还可以指定多个资源。

如果 try 块抛出一个异常，而且 close 方法也抛出一个异常，这就会带来一个难题。

带资源的 try 语句可以很好的处理这种情况，原来的异常会重新抛出，而 close 方法抛出的异常会 "被抑制"。这些异常将自动捕获，并由 addSuppressed 方法增加到原来的异常，可以调用 getSuppressed 方法，他会得到从 close 方法抛出并被抑制的异常列表。


##  分析堆栈轨迹元素

堆栈轨迹 是一个方法调用过程的列表，他包含了程序执行过程中方法调用的特定位置。

可以调用 Throwable 类的 printStackTrace 方法访问堆栈轨迹的文本描述信息

```Java
Throwable t = new Throwable();
StringWriter out = new StringWriter();
t.printStackTrace(new PrintWriter(out));
String description = out.toString();
```

一种更灵活的方法是使用 getStackTrace 方法，他会得到 StackTraceElement 对象的一个数组，可以在程序中分析这个对象数组，例如：

```Java
Throwable t = new Throwable();
StackTraceElement [] frames = t.getStackTrace();
for (StackTraceElement frame : frames) {
    // frame
}
```

StackTraceElement 类含有能够获得文件名和当前执行的代码行号的方法，同时，还含有能够获得类名和方法名的方法，toString 方法将产生一个格式化的字符串，其中包含所获得的信息。

静态的 Thread.getAllStackTrace 方法，他可以产生所有线程的堆栈轨迹，如下所示：

```Java
Map<Thread, StackTraceElement[]> map = Thread.getAllStackTrace();
for (Thread t : map.keySet()) {
    StackTraceElement[] frames = map.get(t);
    ///。。
}

```
----